locale_redirect:
    resource: App\Controller\LocaleRedirectController
    type: attribute

sitemap:
    resource: App\Controller\SitemapController
    type: attribute

shop_controllers:
    resource:
        path: ../src/Controller/Shop/
        namespace: App\Controller\Shop
    type: attribute
    prefix:
        en: /en
        fr: /fr

admin_controllers:
    resource:
        path: ../src/Controller/Admin/
        namespace: App\Controller\Admin
    type: attribute
