<?php

declare(strict_types=1);

namespace App\Tests\Service\Visual;

use App\Entity\Product;
use App\Service\Visual\ImageStorage;
use League\Flysystem\Filesystem;
use League\Flysystem\Local\LocalFilesystemAdapter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Filesystem\Filesystem as SymfonyFilesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;

final class ImageStorageTest extends TestCase
{
    private string $root;
    private ImageStorage $storage;

    protected function setUp(): void
    {
        $this->root = \sys_get_temp_dir().'/asp-image-storage-'.\bin2hex(\random_bytes(4));
        $this->storage = new ImageStorage(new Filesystem(new LocalFilesystemAdapter($this->root)));
    }

    protected function tearDown(): void
    {
        (new SymfonyFilesystem())->remove($this->root);
    }

    public function testSourcePhotoPathIsDerivedFromPosition(): void
    {
        $path = $this->storage->storeSourcePhoto($this->upload('a'), $this->product(), 3);

        self::assertSame('7/sources/03.jpg', $path);
        self::assertStringContainsString('a', $this->storage->read($path));
    }

    /**
     * Regression: positions used to be computed with COUNT(), so deleting the
     * middle photo of three handed the next upload position 3 again — and the
     * write silently replaced the image of the photo still sitting there.
     */
    public function testReusingAPositionNeverOverwritesAnExistingFile(): void
    {
        $product = $this->product();

        $first = $this->storage->storeSourcePhoto($this->upload('original'), $product, 2);
        $second = $this->storage->storeSourcePhoto($this->upload('intruder'), $product, 2);

        self::assertNotSame($first, $second);
        self::assertStringContainsString('original', $this->storage->read($first));
        self::assertStringContainsString('intruder', $this->storage->read($second));
    }

    public function testImportedSourcePhotoAlsoKeepsExistingFiles(): void
    {
        $product = $this->product();
        $sourceFile = \tempnam(\sys_get_temp_dir(), 'asp').'.png';
        \file_put_contents($sourceFile, 'imported');

        $first = $this->storage->storeSourcePhoto($this->upload('original'), $product, 1);
        $second = $this->storage->storeSourcePhotoFromPath($sourceFile, $product, 1);

        \unlink($sourceFile);

        self::assertNotSame($first, $second);
        self::assertStringContainsString('original', $this->storage->read($first));
        self::assertSame('imported', $this->storage->read($second));
    }

    private function product(): Product
    {
        $product = new Product();
        // The id is generated by Doctrine and drives the storage prefix.
        $reflection = new \ReflectionProperty(Product::class, 'id');
        $reflection->setValue($product, 7);

        return $product;
    }

    /**
     * A real JFIF header matters: ImageStorage derives the stored extension
     * from the detected mime type, not from the client-supplied filename.
     */
    private function upload(string $marker): UploadedFile
    {
        $path = \tempnam(\sys_get_temp_dir(), 'asp').'.jpg';
        \file_put_contents(
            $path,
            "\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00".$marker."\xFF\xD9",
        );

        return new UploadedFile($path, 'photo.jpg', 'image/jpeg', null, true);
    }
}
